name: docker_publish_staging

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and push staging docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log into Docker Hub Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image
        run: make ci-build-staging